### ISSUE TITLE
I new help to put mender image yocto in my imx7d-pico

### ISSUE THREAD

**Issue by neuberfran** [jwinarske/clang_toolchain#4]
https://hub.mender.io/t/device-hangs-during-boot-technexion-pico-pi-imx7-yocto/934/3

https://hub.mender.io/t/problems-with-imx-usb-on-pico-pi-imx/1081/33

Help me 

Pls

**Comment by jwinarske** [comment]
Not related to this project...

**Comment by neuberfran** [comment]
And who asked you
