### ISSUE TITLE
libunwind build failed on ubuntu

### ISSUE THREAD

**Issue by CharlesHe023** [jwinarske/clang_toolchain#5]
[21/54] Performing install step for 'compiler-rt'
[0/1] cd /home/hc/render_engine/engine/flutter_embedded/build/toolchain-prefix/src/toolchain-build/compiler-rt-prefix/src/compiler-rt-build && /usr/local/bin/cmake -P cmake_install.cmake
-- Install configuration: "MinSizeRel"
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/include/sanitizer/allocator_interface.h
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/include/sanitizer/asan_interface.h
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/include/sanitizer/common_interface_defs.h
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/include/sanitizer/coverage_interface.h
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/include/sanitizer/dfsan_interface.h
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/include/sanitizer/hwasan_interface.h
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/include/sanitizer/linux_syscall_hooks.h
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/include/sanitizer/lsan_interface.h
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/include/sanitizer/msan_interface.h
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/include/sanitizer/netbsd_syscall_hooks.h
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/include/sanitizer/scudo_interface.h
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/include/sanitizer/tsan_interface.h
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/include/sanitizer/tsan_interface_atomic.h
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/include/xray/xray_interface.h
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/include/xray/xray_log_interface.h
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/include/xray/xray_records.h
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.builtins-armhf.a
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/clang_rt.crtbegin-armhf.o
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/clang_rt.crtend-armhf.o
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.stats-armhf.a
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.stats_client-armhf.a
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.lsan-armhf.a
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.ubsan_standalone-armhf.a
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.ubsan_standalone_cxx-armhf.a
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.ubsan_standalone-armhf.so
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.ubsan_standalone-armhf.a.syms
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.ubsan_standalone_cxx-armhf.a.syms
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.asan-armhf.a
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.asan_cxx-armhf.a
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.asan-preinit-armhf.a
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.asan-armhf.so
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.asan_cxx-armhf.a.syms
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.asan-armhf.a.syms
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/share/asan_blacklist.txt
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.cfi-armhf.a
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.cfi_diag-armhf.a
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/share/cfi_blacklist.txt
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.scudo_minimal-armhf.a
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.scudo_cxx_minimal-armhf.a
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.scudo-armhf.a
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.scudo_cxx-armhf.a
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.scudo_minimal-armhf.so
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.scudo-armhf.so
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.ubsan_minimal-armhf.a
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.ubsan_minimal-armhf.so
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.ubsan_minimal-armhf.a.syms
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.xray-armhf.a
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.xray-fdr-armhf.a
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.xray-basic-armhf.a
-- Installing: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/lib/linux/libclang_rt.xray-profiling-armhf.a
[22/54] Completed 'compiler-rt'
[23/54] Creating directories for 'libunwind'
[24/54] No download step for 'libunwind'
[25/54] No patch step for 'libunwind'
[26/54] No update step for 'libunwind'
[27/54] Performing configure step for 'libunwind'
FAILED: libunwind-prefix/src/libunwind-stamp/libunwind-configure
cd /home/hc/render_engine/engine/flutter_embedded/build/toolchain-prefix/src/toolchain-build/libunwind-prefix/src/libunwind-build && /usr/local/bin/cmake -DCMAKE_TOOLCHAIN_FILE=/home/hc/render_engine/engine/flutter_embedded/build/toolchain-prefix/src/toolchain-build/toolchain.cmake -DCMAKE_INSTALL_PREFIX=/home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/clang/9.0.0/arm-linux-gnueabihf -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_VERBOSE_MAKEFILE=FALSE -DLLVM_CONFIG_PATH=/home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/bin/llvm-config -DLIBUNWIND_STANDALONE_BUILD=OFF -DLIBUNWIND_TARGET_TRIPLE=arm-linux-gnueabihf -DLIBUNWIND_SYSROOT=/home/hc/render_engine/engine/flutter_embedded/sdk/sysroot -DLIBUNWIND_ENABLE_SHARED=ON -ULIBUNWIND_USE_COMPILER_RT=ON -GNinja /home/hc/render_engine/engine/flutter_embedded/third_party/llvm/libunwind && /usr/local/bin/cmake -E touch /home/hc/render_engine/engine/flutter_embedded/build/toolchain-prefix/src/toolchain-build/libunwind-prefix/src/libunwind-stamp/libunwind-configure
-- The C compiler identification is Clang 9.0.0
-- The CXX compiler identification is Clang 9.0.0
-- Check for working C compiler: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/bin/clang
-- Check for working C compiler: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/bin/clang++
-- Check for working CXX compiler: /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LLVM_CONFIG_PATH as /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/bin/llvm-config
-- Linker detection: GNU ld
-- Performing Test LLVM_LIBSTDCXX_MIN
-- Performing Test LLVM_LIBSTDCXX_MIN - Failed
CMake Error at /home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/cmake/llvm/CheckCompilerVersion.cmake:83 (message):
libstdc++ version must be at least 4.8.
Call Stack (most recent call first):
/home/hc/render_engine/engine/flutter_embedded/sdk/toolchain/lib/cmake/llvm/HandleLLVMOptions.cmake:9 (include)
CMakeLists.txt:80 (include)

-- Configuring incomplete, errors occurred!
See also "/home/hc/render_engine/engine/flutter_embedded/build/toolchain-prefix/src/toolchain-build/libunwind-prefix/src/libunwind-build/CMakeFiles/CMakeOutput.log".
See also "/home/hc/render_engine/engine/flutter_embedded/build/toolchain-prefix/src/toolchain-build/libunwind-prefix/src/libunwind-build/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
File "/home/hc/.local/depot_tools/ninjalog_uploader_wrapper.py", line 118, in
sys.exit(main())
File "/home/hc/.local/depot_tools/ninjalog_uploader_wrapper.py", line 76, in main
config = LoadConfig()
File "/home/hc/.local/depot_tools/ninjalog_uploader_wrapper.py", line 31, in LoadConfig
'chromium-build-stats.appspot.com'),
File "/home/hc/.local/depot_tools/ninjalog_uploader.py", line 48, in IsGoogler
_, content = h.request('https://'+server+'/should-upload', 'GET')
File "/home/hc/.local/depot_tools/third_party/httplib2/init.py", line 1694, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "/home/hc/.local/depot_tools/third_party/httplib2/init.py", line 1434, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "/home/hc/.local/depot_tools/third_party/httplib2/init.py", line 1390, in _conn_request
response = conn.getresponse()
File "/usr/lib/python2.7/httplib.py", line 1139, in getresponse
raise ResponseNotReady()
httplib.ResponseNotReady

**Comment by jwinarske** [comment]
Thanks.  I'll take a look when I have time.  To get past this, you can override the toolchain using a pre-built or local build of Clang.

**Comment by CharlesHe023** [comment]
> Thanks. I'll take a look when I have time. To get past this, you can override the toolchain using a pre-built or local build of Clang.

Thanks. I have changed clang to 10.0, but still no luck. Here are more details below:

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/toolchain/bin/clang
Build flags:
Id flags:

The output was:
1
/home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/toolchain/bin/arm-linux-gnueabihf-ld: /lib/../lib/crt1.o: relocations in generic ELF (EM: 3)
/home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/toolchain/bin/arm-linux-gnueabihf-ld: /lib/../lib/crt1.o: error adding symbols: file in wrong format
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/toolchain/bin/clang++
Build flags:
Id flags:

The output was:
1
/home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/toolchain/bin/arm-linux-gnueabihf-ld: /lib/../lib/crt1.o: relocations in generic ELF (EM: 3)
/home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/toolchain/bin/arm-linux-gnueabihf-ld: /lib/../lib/crt1.o: error adding symbols: file in wrong format
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)


Performing C++ SOURCE FILE Test LLVM_LIBSTDCXX_MIN failed with the following output:
Change Dir: /home/qiheng.hc/work/render_engine/clang_toolchain/build/libunwind-prefix/src/libunwind-build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_453d6/fast && gmake[3]: Entering directory `/home/qiheng.hc/work/render_engine/clang_toolchain/build/libunwind-prefix/src/libunwind-build/CMakeFiles/CMakeTmp'
/usr/bin/gmake -f CMakeFiles/cmTC_453d6.dir/build.make CMakeFiles/cmTC_453d6.dir/build
gmake[4]: Entering directory `/home/qiheng.hc/work/render_engine/clang_toolchain/build/libunwind-prefix/src/libunwind-build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_453d6.dir/src.cxx.o
/home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/toolchain/bin/clang++ --target=arm-linux-gnueabihf --sysroot=/home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot    -DLLVM_LIBSTDCXX_MIN  -std=c++0x   -o CMakeFiles/cmTC_453d6.dir/src.cxx.o -c /home/qiheng.hc/work/render_engine/clang_toolchain/build/libunwind-prefix/src/libunwind-build/CMakeFiles/CMakeTmp/src.cxx
Linking CXX executable cmTC_453d6
/home/qiheng.hc/.local/lib/python2.7/site-packages/cmake/data/bin/cmake -E cmake_link_script CMakeFiles/cmTC_453d6.dir/link.txt --verbose=1
/home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/toolchain/bin/clang++ --target=arm-linux-gnueabihf --sysroot=/home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot   -DLLVM_LIBSTDCXX_MIN  -std=c++0x -nodefaultlibs -lc -fuse-ld=lld -v   CMakeFiles/cmTC_453d6.dir/src.cxx.o  -o cmTC_453d6
clang version 10.0.0 (git@gitee.com:horton-cq/llvm-project.git 35627038123b5b391a20e9f4d44a85c7a325027b)
Target: arm-unknown-linux-gnueabihf
Thread model: posix
InstalledDir: /home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/toolchain/bin
Found candidate GCC installation: /home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/usr/lib/gcc/arm-linux-gnueabihf/4.9
Found candidate GCC installation: /home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/usr/lib/gcc/arm-linux-gnueabihf/4.9.4
Found candidate GCC installation: /home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/usr/lib/gcc/arm-linux-gnueabihf/5
Found candidate GCC installation: /home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/usr/lib/gcc/arm-linux-gnueabihf/5.5.0
Found candidate GCC installation: /home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/usr/lib/gcc/arm-linux-gnueabihf/6
Found candidate GCC installation: /home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/usr/lib/gcc/arm-linux-gnueabihf/6.5.0
Found candidate GCC installation: /home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/usr/lib/gcc/arm-linux-gnueabihf/7
Found candidate GCC installation: /home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/usr/lib/gcc/arm-linux-gnueabihf/7.3.0
Found candidate GCC installation: /home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/usr/lib/gcc/arm-linux-gnueabihf/8
Selected GCC installation: /home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/usr/lib/gcc/arm-linux-gnueabihf/8
Candidate multilib: .;@m32
Selected multilib: .;@m32
 "/home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/toolchain/bin/ld.lld" --sysroot=/home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot -EL -X --eh-frame-hdr -m armelf_linux_eabi -dynamic-linker /lib/ld-linux-armhf.so.3 -o cmTC_453d6 /home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/usr/lib/gcc/arm-linux-gnueabihf/8/../../../arm-linux-gnueabihf/crt1.o /home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/usr/lib/gcc/arm-linux-gnueabihf/8/../../../arm-linux-gnueabihf/crti.o /home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/usr/lib/gcc/arm-linux-gnueabihf/8/crtbegin.o -L/home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/usr/lib/gcc/arm-linux-gnueabihf/8 -L/home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/usr/lib/gcc/arm-linux-gnueabihf/8/../../../arm-linux-gnueabihf -L/home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/usr/lib/gcc/arm-linux-gnueabihf/8/../../../../lib -L/home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/lib/arm-linux-gnueabihf -L/home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/lib/../lib -L/home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/usr/lib/arm-linux-gnueabihf -L/home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/usr/lib/../lib -L/home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/usr/lib/arm-linux-gnueabihf/../../lib -L/home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/usr/lib/gcc/arm-linux-gnueabihf/8/../../.. -L/home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/lib -L/home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/usr/lib -lc CMakeFiles/cmTC_453d6.dir/src.cxx.o /home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/usr/lib/gcc/arm-linux-gnueabihf/8/crtend.o /home/qiheng.hc/work/render_engine/flutter_sdk_root/sdk/sysroot/usr/lib/gcc/arm-linux-gnueabihf/8/../../../arm-linux-gnueabihf/crtn.o
ld.lld: error: undefined symbol: std::bad_function_call::what() const
>>> referenced by src.cxx
>>>               CMakeFiles/cmTC_453d6.dir/src.cxx.o:(chk)
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[4]: *** [cmTC_453d6] Error 1
gmake[4]: Leaving directory `/home/qiheng.hc/work/render_engine/clang_toolchain/build/libunwind-prefix/src/libunwind-build/CMakeFiles/CMakeTmp'
gmake[3]: *** [cmTC_453d6/fast] Error 2
gmake[3]: Leaving directory `/home/qiheng.hc/work/render_engine/clang_toolchain/build/libunwind-prefix/src/libunwind-build/CMakeFiles/CMakeTmp'


Source file was:

#include <iosfwd>
#if defined(__GLIBCXX__)
#if __GLIBCXX__ < 20150422
#error Unsupported libstdc++ version
#endif
#endif
#if defined(__GLIBCXX__)
extern const char _ZNKSt17bad_function_call4whatEv[];
const char *chk = _ZNKSt17bad_function_call4whatEv;
#else
const char *chk = "";
#endif
int main() { ++chk; return 0; }

**Comment by CharlesHe023** [comment]
Hi  jwinarske,
I have added -DLLVM_COMPILER_CHECKED=TRUE to skip compiler check, now I get configure error for libcxxabi: 
````
CMake Error at src/CMakeLists.txt:256 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_LINKER_FILE:unwind_static>

  No target "unwind_static"


CMake Error at src/CMakeLists.txt:256 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_LINKER_FILE:unwind_static>

  No target "unwind_static"
```

**Comment by jwinarske** [comment]
Hi @ffzwadd.  A couple of thoughts.

The llvm-project moved to git, and it's streamlined.  I'm working on support for this.

The flutter engine build pulls in a pre-built clang tool chain.  Depending on your host, you can cross-compile without much effort.  I've recently added meta-flutter which uses this model.  At some point I'm going to update my emersed flutter repo to use this scheme.

What hardware are you targeting, what's your host environment?

**Comment by CharlesHe023** [comment]
Hi jwinarske,
    Actually, I have tried change llvm-project repos to git, but I still experienced the same error. 😢 I think use a pre-built clang tool chain is a good idea. My target hardware is raspberry pi 4 and the host enviroment is Cent OS 7.0 64bit(It's a virtual machine on the cloud, I do not have root access).
Thanks and best regards,
Charles

**Comment by jwinarske** [comment]
I see.  I started a new branch for my change.  It should be ready in ~a week.

Yeah I've seen llvm devs complain about this error on the llvm mailing list; unrelated to me.

Cheers,
Joel

**Comment by CharlesHe023** [comment]
OK, I'll try your new branch later. Thanks for your help.

**Comment by jwinarske** [comment]
You can pull a CIPD package of Clang 11.  It has aarch, arm, x86, and x86_64.  I'll post up the command sequence.
